/**
 * INGLY ADMIN PANEL - MOCK DATA
 * TZ.txt talablari va 4000 Essential English Words ma'lumotlariga to'liq mos.
 */

export const mockStats = {
  totalUsers: 14850,
  activeToday: 3240,
  wordsLearned: 184520,
  streakChampions: 412,
  userGrowthPct: '+14.8%',
  activeGrowthPct: '+8.2%',
  wordsGrowthPct: '+22.5%',
  booksProgress: [
    { book: 1, title: 'Book 1 (Elementary)', progress: 84, activeUsers: 6420, color: '#38BDF8' },
    { book: 2, title: 'Book 2 (Pre-Int)', progress: 62, activeUsers: 4190, color: '#0EA5E9' },
    { book: 3, title: 'Book 3 (Intermediate)', progress: 41, activeUsers: 2540, color: '#5B4DFF' },
    { book: 4, title: 'Book 4 (Upper-Int)', progress: 28, activeUsers: 1100, color: '#8B5CF6' },
    { book: 5, title: 'Book 5 (Advanced)', progress: 14, activeUsers: 420, color: '#EC4899' },
    { book: 6, title: 'Book 6 (Proficiency)', progress: 7, activeUsers: 180, color: '#F59E0B' },
  ],
};

export const mockWords = [
  {
    id: 1,
    book: 1,
    unit: 1,
    word: 'Afraid',
    phonetic: '/əˈfreɪd/',
    pos: 'adjective',
    uzbek: "Qo'rqqan",
    definition: 'When someone is afraid, they feel fear.',
    definition_uz: "Biror kimsa qo'rqqanda, u xavf yoki vahimani his qiladi.",
    example: 'The woman was afraid of what she saw.',
    example_uz: 'Ayol ko\'rgan narsasidan qo\'rqib ketdi.',
    image_url: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?w=400&q=80',
    audio_url: 'https://cdn.ingly.uz/audio/b1/u1/afraid.mp3',
    video_clip_url: 'https://cdn.ingly.uz/videos/clips/afraid_harry_potter.mp4',
    movie_title: 'Harry Potter & The Sorcerer\'s Stone',
  },
  {
    id: 2,
    book: 1,
    unit: 1,
    word: 'Agree',
    phonetic: '/əˈɡriː/',
    pos: 'verb',
    uzbek: 'Rozi bo\'lmoq, fikriga qo\'shilmoq',
    definition: 'To agree is to have the same opinion or say yes.',
    definition_uz: 'Rozi bo\'lish — bir xil fikrda bo\'lish yoki "ha" deb javob berishdir.',
    example: 'The food is very good in that restaurant. I agree with you.',
    example_uz: 'U restoranda taomlar juda mazali. Fikringizga qo\'shilaman.',
    image_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&q=80',
    audio_url: 'https://cdn.ingly.uz/audio/b1/u1/agree.mp3',
    video_clip_url: 'https://cdn.ingly.uz/videos/clips/agree_friends.mp4',
    movie_title: 'Friends S04E12',
  },
  {
    id: 3,
    book: 1,
    unit: 1,
    word: 'Angry',
    phonetic: '/ˈæŋɡri/',
    pos: 'adjective',
    uzbek: 'Jahli chiqqan, g\'azablangan',
    definition: 'When someone is angry, they want to speak loudly or fight.',
    definition_uz: 'Kimningdir jahli chiqqanda, u baland ovozda baqirishni yoki janjallashishni istaydi.',
    example: 'She didn\'t do her homework, so her father was angry.',
    example_uz: 'U uy vazifasini bajarmadi, shuning uchun otasining jahli chiqdi.',
    image_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=400&q=80',
    audio_url: 'https://cdn.ingly.uz/audio/b1/u1/angry.mp3',
    video_clip_url: 'https://cdn.ingly.uz/videos/clips/angry_avengers.mp4',
    movie_title: 'The Avengers (Hulk)',
  },
  {
    id: 4,
    book: 1,
    unit: 1,
    word: 'Arrive',
    phonetic: '/əˈraɪv/',
    pos: 'verb',
    uzbek: 'Yetib kelmoq',
    definition: 'To arrive is to get to or reach some place.',
    definition_uz: 'Yetib kelish — biror manzilga borish yoki qadam bosishdir.',
    example: 'The bus always arrives at the station on time.',
    example_uz: 'Avtobus bekatga doimo o\'z vaqtida yetib keladi.',
    image_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400&q=80',
    audio_url: 'https://cdn.ingly.uz/audio/b1/u1/arrive.mp3',
    video_clip_url: 'https://cdn.ingly.uz/videos/clips/arrive_spiderman.mp4',
    movie_title: 'Spider-Man: Homecoming',
  },
  {
    id: 5,
    book: 1,
    unit: 1,
    word: 'Attack',
    phonetic: '/əˈtæk/',
    pos: 'verb',
    uzbek: 'Hujum qilmoq',
    definition: 'To attack is to try to fight or hurt someone.',
    definition_uz: 'Hujum qilish — kimgadir qarshi jangga kirish yoki unga zarar yetkazishga urinishdir.',
    example: 'The man wanted to attack the monster with his sword.',
    example_uz: 'Kishi qilichi bilan maxluqqa hujum qilmoqchi bo\'ldi.',
    image_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=400&q=80',
    audio_url: 'https://cdn.ingly.uz/audio/b1/u1/attack.mp3',
    video_clip_url: 'https://cdn.ingly.uz/videos/clips/attack_gladiator.mp4',
    movie_title: 'Gladiator',
  },
];

export const mockUsers = [
  {
    id: 'u-101',
    full_name: 'Anvar Qodirov',
    username: 'anvar_dev',
    phone: '+998 90 123 45 67',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&q=80',
    current_book: 2,
    current_unit: 14,
    words_mastered: 420,
    current_streak: 18,
    is_premium: false,
    is_blocked: false,
    created_at: '2026-08-12',
    last_login_at: '2026-10-03 11:45',
  },
  {
    id: 'u-102',
    full_name: 'Madina Karimova',
    username: 'madina_k',
    phone: '+998 93 987 65 43',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    current_book: 4,
    current_unit: 8,
    words_mastered: 960,
    current_streak: 42,
    is_premium: true,
    is_blocked: false,
    created_at: '2026-07-04',
    last_login_at: '2026-10-03 13:12',
  },
  {
    id: 'u-103',
    full_name: 'Javohir Toshmatov',
    username: 'javohir_99',
    phone: '+998 97 555 12 34',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=100&q=80',
    current_book: 1,
    current_unit: 4,
    words_mastered: 60,
    current_streak: 2,
    is_premium: false,
    is_blocked: true,
    created_at: '2026-09-20',
    last_login_at: '2026-09-29 08:30',
  },
  {
    id: 'u-104',
    full_name: 'Zuhra Aliyeva',
    username: 'zuhra_ali',
    phone: '+998 94 444 88 99',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&q=80',
    current_book: 3,
    current_unit: 22,
    words_mastered: 740,
    current_streak: 25,
    is_premium: false,
    is_blocked: false,
    created_at: '2026-08-30',
    last_login_at: '2026-10-03 09:15',
  },
];

export const mockAdmins = [
  {
    id: 'adm-01',
    full_name: 'Super Admin (Bosh Arxitektor)',
    username: 'ingly_super',
    role: 'super_admin',
    role_label: 'Super Admin',
    permissions: ['manage_words', 'manage_users', 'manage_admins', 'view_stats', 'send_push', 'manage_settings'],
    is_active: true,
  },
  {
    id: 'adm-02',
    full_name: 'Bobur Shokirov',
    username: 'bobur_editor',
    role: 'editor',
    role_label: 'Kontent Menejer',
    permissions: ['manage_words', 'view_stats'],
    is_active: true,
  },
  {
    id: 'adm-03',
    full_name: 'Nodira Azimova',
    username: 'nodira_mod',
    role: 'moderator',
    role_label: 'Moderator',
    permissions: ['manage_users', 'view_stats', 'send_push'],
    is_active: true,
  },
];

export const mockFeatureFlags = {
  // TZ.txt 9.5: Reklama switch (Google AdMob) - Hozirda 100% O'CHIQ
  adsEnabled: false,
  // TZ.txt 9.5: Pullik obuna switch (VIP / Premium) - Hozirda O'CHIQ
  premiumModeEnabled: false,
  freeBooksCount: 2, // Agar obuna yoqilsa: Book 1-2 bepul, Book 3-6 pullik
  monthlyPriceUzs: 29000,
  yearlyPriceUzs: 199000,
  smartCacheEnabled: true,
  offlineModeAllowed: true,
};

export const mockPushTemplates = [
  {
    id: 'tpl-1',
    title: 'Streak olovini asrang! 🔥',
    body: "🔥 7 kunlik streak'ingiz o'chib qolmasin! 5 ta so'z yodlang va olovni saqlang.",
    category: 'streak',
  },
  {
    id: 'tpl-2',
    title: 'Qahva vaqti! ☕',
    body: '☕ Qahvangiz sovumasidan oldin bugungi 5 ta yangi so\'z bilan tanishib olaylikmi?',
    category: 'engagement',
  },
  {
    id: 'tpl-3',
    title: 'So\'zlaringiz kutyapti 👀',
    body: '👀 Bugungi so\'zlaringiz sizni kuta-kuta zerikib qoldi. 3 daqiqa vaqt ajrata olasizmi?',
    category: 'reminder',
  },
  {
    id: 'tpl-4',
    title: 'Ingliz tilida o\'ylash vaqti! 🧠',
    body: '🧠 Bugun ingliz tilida o\'ylash vaqti keldi! Yangi unit eshikni taqillatyapti.',
    category: 'learning',
  },
  {
    id: 'tpl-5',
    title: 'Do\'stlaringiz peshqadam! ⚡',
    body: '⚡ Do\'stlaringiz allaqachon bugungi darsni tugatishdi. Siz qachon boshlaysiz?',
    category: 'social',
  },
];
